/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AudioInput {
    /**
    * Base64-encoded audio bytes.
    */
    'content': string;
    /**
    * Audio encoding of the provided bytes.
    */
    'encoding': AudioInput.EncodingEnum;
    /**
    * Sampling rate in Hz (required for raw formats like mulaw/pcm_s16le).
    */
    'sampleRateHz'?: number;
    /**
    * Number of channels (1=mono, 2=stereo).
    */
    'channels'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "content",
            "baseName": "content",
            "type": "string"
        },
        {
            "name": "encoding",
            "baseName": "encoding",
            "type": "AudioInput.EncodingEnum"
        },
        {
            "name": "sampleRateHz",
            "baseName": "sample_rate_hz",
            "type": "number"
        },
        {
            "name": "channels",
            "baseName": "channels",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return AudioInput.attributeTypeMap;
    }
}

export namespace AudioInput {
    export enum EncodingEnum {
        Mulaw = <any> 'mulaw',
        Alaw = <any> 'alaw',
        PcmS16le = <any> 'pcm_s16le',
        Wav = <any> 'wav',
        Mp3 = <any> 'mp3',
        Opus = <any> 'opus'
    }
}
