/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Optional per-class scores/probabilities.
*/
export class DetectResponseScores {
    'real'?: number;
    'fake'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "real",
            "baseName": "real",
            "type": "number"
        },
        {
            "name": "fake",
            "baseName": "fake",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DetectResponseScores.attributeTypeMap;
    }
}

