/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DetectRequestOptions {
    /**
    * If true, return per-class probability scores in addition to prediction/confidence.
    */
    'returnScores'?: boolean = false;
    /**
    * Optional override threshold for labeling fake vs real (model still returns raw scores).
    */
    'threshold'?: number;
    /**
    * Optional calibration profile name (e.g., \"default\", \"bank_v1\").
    */
    'calibrationProfile'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "returnScores",
            "baseName": "return_scores",
            "type": "boolean"
        },
        {
            "name": "threshold",
            "baseName": "threshold",
            "type": "number"
        },
        {
            "name": "calibrationProfile",
            "baseName": "calibration_profile",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return DetectRequestOptions.attributeTypeMap;
    }
}

