/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DetectResponseScores } from './detectResponseScores';

export class DetectResponse {
    'prediction': DetectResponse.PredictionEnum;
    /**
    * Confidence of the returned prediction (calibrated as best-effort).
    */
    'confidence': number;
    /**
    * Server-generated id for debugging/support.
    */
    'requestId': string;
    /**
    * Server-side processing time in milliseconds.
    */
    'processingMs'?: number;
    'scores'?: DetectResponseScores;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "prediction",
            "baseName": "prediction",
            "type": "DetectResponse.PredictionEnum"
        },
        {
            "name": "confidence",
            "baseName": "confidence",
            "type": "number"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "processingMs",
            "baseName": "processing_ms",
            "type": "number"
        },
        {
            "name": "scores",
            "baseName": "scores",
            "type": "DetectResponseScores"
        }    ];

    static getAttributeTypeMap() {
        return DetectResponse.attributeTypeMap;
    }
}

export namespace DetectResponse {
    export enum PredictionEnum {
        Real = <any> 'real',
        Fake = <any> 'fake'
    }
}
