/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { AudioInput } from './audioInput';
import { DetectRequestOptions } from './detectRequestOptions';

export class DetectRequest {
    /**
    * Optional client-generated correlation id (e.g., Twilio CallSid).
    */
    'sessionId'?: string;
    'audio': AudioInput;
    'options'?: DetectRequestOptions;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessionId",
            "baseName": "session_id",
            "type": "string"
        },
        {
            "name": "audio",
            "baseName": "audio",
            "type": "AudioInput"
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "DetectRequestOptions"
        }    ];

    static getAttributeTypeMap() {
        return DetectRequest.attributeTypeMap;
    }
}

