/**
 * NuVoice Fraud Detection API
 * Single-serving fraud/deepfake detection over audio. 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ErrorResponseError {
    /**
    * Stable machine-readable error code.
    */
    'code': string;
    'message': string;
    /**
    * Present when available for debugging/support.
    */
    'requestId'?: string;
    /**
    * Optional structured error details.
    */
    'details'?: { [key: string]: any; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string"
        },
        {
            "name": "requestId",
            "baseName": "request_id",
            "type": "string"
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "{ [key: string]: any; }"
        }    ];

    static getAttributeTypeMap() {
        return ErrorResponseError.attributeTypeMap;
    }
}

